version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/test
permissions:
  - object: /home/ec2-user/test/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 500
      runas: ec2-user
